//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeasBank.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IdeasBankEntities : DbContext
    {
        public IdeasBankEntities()
            : base("name=IdeasBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Comments> Comments { get; set; }
        public DbSet<Ideas> Ideas { get; set; }
        public DbSet<Likes> Likes { get; set; }
        public DbSet<Photos> Photos { get; set; }
        public DbSet<Subscribes> Subscribes { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
