//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeasBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribe
    {
        public int IdeaId { get; set; }
        public int AuthorId { get; set; }
    }
}
